#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'lunasvg'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
'plutovg.c',
'plutovg-paint.c',
'plutovg-geometry.c',
'plutovg-blend.c',
'plutovg-rle.c',
'plutovg-dash.c',
'plutovg-ft-raster.c',
'plutovg-ft-stroker.c',
'plutovg-ft-math.c',
'lunasvg.cpp',
'element.cpp',
'property.cpp',
'parser.cpp',
'layoutcontext.cpp',
'canvas.cpp',
'clippathelement.cpp',
'defselement.cpp',
'gelement.cpp',
'geometryelement.cpp',
'graphicselement.cpp',
'maskelement.cpp',
'markerelement.cpp',
'paintelement.cpp',
'stopelement.cpp',
'styledelement.cpp',
'styleelement.cpp',
'svgelement.cpp',
'symbolelement.cpp',
'useelement.cpp',
	]
	
	if bld.env.DEST_OS == 'win32':
		source += [
		]

	includes = [
		'.',
		'../public',
		'../public/lunasvg',
		'../public/tier0',
		'../public/tier1',
		'../thirdparty/stb'
	]

	defines = ['RAD_TELEMETRY_DISABLED', 'lunasvg_EXPORTS']

	libs = []
	
	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = bld.env.LIBDIR,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

