#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'video_bink'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'bink_video.cpp',
		'bink_material.cpp',
		'yuv_rgb.c'
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common',
		'../'
	] + bld.env.INCLUDES_SDL2
	if bld.env.DEST_OS == 'android':
		includes += [
			'../../ffmpeg/'+bld.env.DEST_CPU+'/']
	else:
		includes += [
			'../../ffmpeg/aarch64/']
	defines = []
	libs = ['tier0','tier1','tier2','tier3','vstdlib']
	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']
	else:
		bld.env.LIB = ['avutil', 'avformat', 'avcodec']
		libs += ['AVCODEC', 'AVUTIL', 'AVFORMAT']

	install_path = bld.env.LIBDIR

	if True:  #not bld.env.DEST_OS == 'android':
		bld.shlib(
			source   = source,
			target   = PROJECT_NAME,
			name     = PROJECT_NAME,
			features = 'c cxx',
			includes = includes,
			defines  = defines,
			use      = libs,
			install_path = install_path,
			subsystem = bld.env.MSVC_SUBSYSTEM,
			idx      = bld.get_taskgen_count()
		)

